[package]
name = "aqora-config"
version = "0.9.0"
edition = "2021"
publish = false

[dependencies]
pep440_rs = { version = "0.7" }
pep508_rs = "0.9"
pyproject-toml = "0.13"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
toml = "0.8"
