[package]
name = "aqora-config"
version = "0.5.0"
edition = "2021"
publish = false

[dependencies]
pep440_rs = { version = "0.5", features = ["serde"] }
pep508_rs = "0.4"
pyproject-toml = "0.10"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
toml = "0.8"
